### PR TITLE
maoxin_homework_1

### PR DESCRIPTION
**Pull request by maoxin**
``` r
init <- function(len_1, len_2, gamma) {
  mtrx <- matrix(, nrow=len_1+1, ncol=len_2+1)
  mtrx[1,] <- (0:len_2) * (-gamma)
  mtrx[,1] <- (0:len_1) * (-gamma)

  return(mtrx)
}

main <- function(str_1, str_2, alpha, beta, gamma) {
  str_1 <- strsplit(str_1, "")[[1]]
  str_2 <- strsplit(str_2, "")[[1]]
  len_1 <- length(str_1)
  len_2 <- length(str_2)
  mtrx <- init(len_1, len_2, gamma)
  path_mtrx <- matrix(, nrow=len_1+1, ncol=len_2+1)

  for (i in 1:(len_1*len_2)) {
    rindex <- 2 + trunc((i-1) / len_2)
    cindex <- 1 + i - trunc((i-1) / len_2) * len_2
    l <- mtrx[rindex, cindex-1] - gamma
    u <- mtrx[rindex-1, cindex] - gamma

    if (str_1[rindex-1] == str_2[cindex-1]) {
      lu <- mtrx[rindex-1, cindex-1] + alpha
    }
    else {
      lu <- mtrx[rindex-1, cindex-1] - beta
    }

    l_u_lu <- c(l, u, lu)
    index_l_u_lu <- c((cindex-2)*(len_1+1)+rindex, (cindex-1)*(len_1+1)+rindex-1, (cindex-2)*(len_1+1)+rindex-1)

    mtrx[rindex, cindex] <- max(l, u, lu)
    foo <- index_l_u_lu[which(l_u_lu==max(l_u_lu))]
    path_mtrx[rindex, cindex] <- tail(index_l_u_lu[which(l_u_lu==max(l_u_lu))], n=1)
  }

  return(list(mtrx=mtrx, path_mtrx=path_mtrx))
}

f <- readLines("/Users/maoxin/Desktop/homework/bioinfo/HomeworkI/LongestCommonSeq.txt")
str_1 <- f[1]
str_2 <- f[2]

r <- main(str_1, str_2, 1, 0, 0)

print(r$mtrx)
print(r$path_mtrx)
max_position <- tail(which(r$mtrx==max(r$mtrx)), n=1)

path <- c(max_position)
while (!is.na(max_position)) {
  max_position <- r$path_mtrx[max_position]
  path <- append(path, max_position)
}
```

### CODE REVIEW

**Comment by maoxin** [comment]
The score is 1050

**Comment by beyondpie** [comment]
Hi, Maoxin,
Could you please also show the mathed string you get in the second problem?
Songpeng

**Comment by maoxin** [comment]
Oh, I just found that I haven't implement the function to extract the string. And I will update my code here.

**Comment by maoxin** [comment]
``` R
init <- function(len_1, len_2, gamma) {
  mtrx <- matrix(, nrow=len_1+1, ncol=len_2+1)
  mtrx[1,] <- (0:len_2) * (-gamma)
  mtrx[,1] <- (0:len_1) * (-gamma)

  return(mtrx)
}

main <- function(str_1, str_2, alpha, beta, gamma) {
  str_1 <- strsplit(str_1, "")[[1]]
  str_2 <- strsplit(str_2, "")[[1]]
  len_1 <- length(str_1)
  len_2 <- length(str_2)
  mtrx <- init(len_1, len_2, gamma)
  path_mtrx <- matrix(, nrow=len_1+1, ncol=len_2+1)

  for (i in 1:(len_1*len_2)) {
    rindex <- 2 + trunc((i-1) / len_2)
    cindex <- 1 + i - trunc((i-1) / len_2) * len_2
    l <- mtrx[rindex, cindex-1] - gamma
    u <- mtrx[rindex-1, cindex] - gamma

    if (str_1[rindex-1] == str_2[cindex-1]) {
      lu <- mtrx[rindex-1, cindex-1] + alpha
    }
    else {
      lu <- mtrx[rindex-1, cindex-1] - beta
    }

    l_u_lu <- c(l, u, lu)
    index_l_u_lu <- c((cindex-2)*(len_1+1)+rindex, (cindex-1)*(len_1+1)+rindex-1, (cindex-2)*(len_1+1)+rindex-1)

    mtrx[rindex, cindex] <- max(l_u_lu)
    foo <- index_l_u_lu[which(l_u_lu==max(l_u_lu))]
    path_mtrx[rindex, cindex] <- tail(index_l_u_lu[which(l_u_lu==max(l_u_lu))], n=1)
  }

  return(list(mtrx=mtrx, path_mtrx=path_mtrx))
}

f <- readLines("/Users/maoxin/Desktop/homework/bioinfo/HomeworkI/LongestCommonSeq.txt")
str_1 <- f[1]
str_2 <- f[2]

r <- main(str_1, str_2, 1, 0, 0)

str_1 <- strsplit(str_1, "")[[1]]
str_2 <- strsplit(str_2, "")[[1]]
max_position <- tail(which(r$mtrx==max(r$mtrx)), n=1)
path <- c(max_position)
while (!is.na(max_position)) {
  max_position <- r$path_mtrx[max_position]

  if (!is.na(max_position)) {
    path <- append(path, max_position)
  }
}

path <- rev(path)
str_match <- vector()

for (i in tail(path, n=length(path)-1)) {
  col <- trunc((i-1) / (length(str_1) + 1))
  row <- i - trunc((i-1)/(length(str_1)+1)) * (length(str_1) + 1) - 1

  if (str_1[row] == str_2[col]) {
    str_match <- append(str_match, str_2[col])
  }
}

str_match <- paste(str_match, collapse='')
```

**Comment by maoxin** [comment]
And the final result is:

```
"Bioinformatics is the application of information technology to the field of molecular biology. The term bioinformatics was coined by Paulien Hogeweg in 1979 for the study of informatic processes in biotic systems. Bioinformatics now entails the creation and advancement of databases, algorithms, computational and statistical techniques, and theory to solve formal and practical problems arising from the management and analysis of biological data. Over the past few decades rapid developments in genomic and other molecular research technologies and developments in information technologies have combined to produce a tremendous amount of information related to molecular biology. It is the name given to these mathematical and computing approaches used to glean understanding of biological processes. Common activities in bioinformatics include mapping and analyzing DNA and protein sequences, aligning different DNA and protein sequences to compare them and creating and viewing 3-D models of protein structures."
```

**Comment by beyondpie** [comment]
OK, thanks a lot!
Songpeng

**Comment by maoxin** [comment]
R spent a lot of time....

**Comment by beyondpie** [comment]
You got it~
BTW, U can see other students codes in the request part (I label them in red).
Songpeng

**Comment by maoxin** [comment]
That's good! I'll have a look.
BTW, would Python be faster?

**Comment by beyondpie** [comment]
I think python will also be slow if you use the similar type because both python and R are “解释型语言”.
[1] http://baike.baidu.com/view/1233576.htm

**Comment by maoxin** [comment]
Ok, I got it. Thanks!

**Comment by beyondpie** [comment]
https://github.com/xhythu/Introduction-to-Bioinformatics
Houyuan wrote the python version, and it was indeed slow. He also tried Rcpp, which could accelerate R code much faster~
Songpeng

**Comment by maoxin** [comment]
I haven't tried Rcpp yet. I will consider it the next time~

**Pull request closed without merging**
