### PR TITLE
ZhengdaZhu_Homework_1

### PR DESCRIPTION
**Pull request by zhuzd12**
我不太明白第二问我读取的txt是一堆乱码，但是整体算法实现了。下面是我的代码，希望助教批评指正。另外弱弱的问下，在git是不是只有一次提交机会~~

``` R
seq_alig<-function(s,t,a=1,b=-1,c=-1){ #s,t为比对字符串；a,b,c代表惩罚值
  n<-nchar(s)
  m<-nchar(t)
  mat<-array(0,c(n+1,m+1)) #存储获得分数
  flag<-array(0,c(n+1,m+1)) #存储每点的前驱路径信息
  path<-array(0,c(n+1,m+1))  #存储路径信息，1代表路径点
  path[1,1]=1
  path[n+1,m+1]=1
  for(i in 2:(m+1)){  #分数矩阵第一行的初始化
    mat[1,i]<-(i-1)*c
    flag[1,i]<-3
  }
  for(i in 2:(n+1)){  #分数矩阵第一列的初始化
    mat[i,1]<-(i-1)*c
    flag[i,1]<-2
  }
  k=1;
  for(i in 2:(n+1)){  #动态规划求取分数矩阵和路径
    for(j in 2:(m+1)){
      if(substr(s,i-1,i-1)==substr(t,j-1,j-1)){
        w<-a
        k<-1
      }
      else{
        w<-b
        k<--1
      }
      co<-c(mat[i-1,j-1]+w,mat[i-1,j]+c,mat[i,j-1]+c)
      mat[i,j]<-max(co)
      flag[i,j]<-k*which.max(co)
    }
  }
  i<-n+1
  j<-m+1
  str<-NULL
  k<-0
  while(i>1||j>1){  #得到最大串匹配
    q=flag[i,j]
    if(q==1||q==-1){
      i<-i-1
      j<-j-1
      if(q==1){
        str<-paste(substr(s,i,i),str)
        k<-k+1
      }
    }
    if(q==2||q==-2){
      i<-i-1
    }
    if(q==3||q==-3){
      j<-j-1
    }
    path[i,j]<-1
  }

  print("全局匹配分数:")
  print(mat[n+1,m+1])
  print("匹配路径：")
  print(path)
  print("最大共有子串:")
  print(str)
  print("最大共有子串的长度")
  print(k)
}
```

### CODE REVIEW

**Comment by beyondpie** [comment]
Hi, Zhengda,
We have no limitations for your submit. 
1. Would you mind to show your result on the second question?
2. You'd better use English annotations for your codes (also for your file).

**Comment by zhuzd12** [comment]
Sorry for my mistake. I have tried to deal the second question, but it turns out to be an error because the string is so long(each has 10000 characters) that I can not  apply for the matrix big enough.  I have no idea how to cope with it.The following is the error message.
image
The way to read string: 
w<-scan("LongestCommonSeq.txt",what=character(),sep="\n",comment.char = "")
The revised code:

``` R
# s and t represent the strings to compare
# a(b) represent the bonus(punishment) for single character matching
# c represent the punishment for matching the null
seq_alig<-function(s,t,a=1,b=-1,c=-1){
  n<-nchar(s)
  m<-nchar(t)
  mat<-array(0,c(n+1,m+1)) #this matrix stores cost of optimum alignment
  flag<-array(0,c(n+1,m+1)) #this matrix stores the optimum precursor for every point
  path<-array(0,c(n+1,m+1))  #this matrix records the information about the optimum path
  # (I use '1' to mark the point on the path)
  path[1,1]=1
  path[n+1,m+1]=1
  for(i in 2:(m+1)){  #initialization for the first row
    mat[1,i]<-(i-1)*c
    flag[1,i]<-3
  }
  for(i in 2:(n+1)){  #initialization for the first col
    mat[i,1]<-(i-1)*c
    flag[i,1]<-2
  }
  k=1;
  for(i in 2:(n+1)){  # dynamic programming
    for(j in 2:(m+1)){
      if(substr(s,i-1,i-1)==substr(t,j-1,j-1)){
        w<-a
        k<-1
      }
      else{
        w<-b
        k<--1
      }
      co<-c(mat[i-1,j-1]+w,mat[i-1,j]+c,mat[i,j-1]+c)
      mat[i,j]<-max(co)
      flag[i,j]<-k*which.max(co)
    }
  }
  i<-n+1
  j<-m+1
  str<-NULL
  k<-0
  while(i>1||j>1){  # maximal matching of strings
    q=flag[i,j]
    if(q==1||q==-1){
      i<-i-1
      j<-j-1
      if(q==1){
        str<-paste(substr(s,i,i),str) # Increments a character in each loop iteration
        k<-k+1
      }
    }
    if(q==2||q==-2){
      i<-i-1
    }
    if(q==3||q==-3){
      j<-j-1
    }
    path[i,j]<-1
  }

  print("cost of optimum alignment:")
  print(mat[n+1,m+1])
  #print("matching path：")
  #print(path)
  print("maximal matching of strings:")
  print(str)
  print("the length of maximal matching of strings")
  print(k)
}
```

**Comment by beyondpie** [comment]
Hi, Zhengda,
Your personal computer cannot allocate around 1G space ?
Songpeng

**Comment by zhuzd12** [comment]
Hi TA
I am pretty sure that it 's a problem of insufficient memory.
image

**Comment by beyondpie** [comment]
Hi, Zhengda,
1. So you use R on Windows? If it is true, you can try to use 

``` R
memory.limit()
```

to allow R to allocate more RAM than the default.
2.  You also open one MATLAB when you run the R codes? What happens if you close it, and just run r.
3.  Would you mind to show all your source code including how you deal with the second one for me ? You can add the file in your own repository, and give me the link~
      Songpeng

**Comment by zhuzd12** [comment]
Hi TA
I got this problem solved by using R on Ubuntu. And finally I found  something meaningful hiding in the two strings in the second question. I'm sorry for my previous mistakes. 
Besides, I cope with the two questions in one procedure.  And it will be clear after you read my annotations. 
The address of my source code: https://github.com/zhuzd12/Intro2CompBio 
 Branch name:homework1
The following is the result of the second question:

```
B i o i n f o r m a t i c s   i s   t h e   a p p l i c a t i o n   o f   i n f o r m a t i o n   t e c h n o l o g y   t o   t h e   f i e l d   o f   m o l e c u l a r   b i o l o g y .   T h e   t e r m   b i o i n f o r m a t i c s   w a s   c o i n e d   b y   P a u l i e n   H o g e w e g   i n   1 9 7 9   f o r   t h e   s t u d y   o f   i n f o r m a t i c   p r o c e s s e s   i n   b i o t i c   s y s t e m s .   B i o i n f o r m a t i c s   n o w   e n t a i l s   t h e   c r e a t i o n   a n d   a d v a n c e m e n t   o f   d a t a b a s e s ,   a l g o r i t h m s ,   c o m p u t a t i o n a l   a n d   s t a t i s t i c a l   t e c h n i q u e s ,   a n d   t h e o r y   t o   s o l v e   f o r m a l   a n d   p r a c t i c a l   p r o b l e m s   a r i s i n g   f r o m   t h e   m a n a g e m e n t   a n d   a n a l y s i s   o f   b i o l o g i c a l   d a t a .   O v e r   t h e   p a s t   f e w   d e c a d e s   r a p i d   d e v e l o p m e n t s   i n   g e n o m i c   a n d   o t h e r   m o l e c u l a r   r e s e a r c h   t e c h n o l o g i e s   a n d   d e v e l o p m e n t s   i n   i n f o r m a t i o n   t e c h n o l o g i e s   h a v e   c o m b i n e d   t o   p r o d u c e   a   t r e m e n d o u s   a m o u n t   o f   i n f o r m a t i o n   r e l a t e d   t o   m o l e c u l a r   b i o l o g y .   I t   i s   t h e   n a m e   g i v e n   t o   t h e s e   m a t h e m a t i c a l   a n d   c o m p u t i n g   a p p r o a c h e s   u s e d   t o   g l e a n   u n d e r s t a n d i n g   o f   b i o l o g i c a l   p r o c e s s e s .   C o m m o n   a c t i v i t i e s   i n   b i o i n f o r m a t i c s   i n c l u d e   m a p p i n g   a n d   a n a l y z i n g   D N A   a n d   p r o t e i n   s e q u e n c e s ,   a l i g n i n g   d i f f e r e n t   D N A   a n d   p r o t e i n   s e q u e n c e s   t o   c o m p a r e   t h e m   a n d   c r e a t i n g   a n d   v i e w i n g   3 - D   m o d e l s   o f   p r o t e i n   s t r u c t u r e s . 
```

**Comment by beyondpie** [comment]
That's really a great job~
BTW, how long you run the code? Since the two strings are quite long, it might take lots of time using _double for loop_ in R.

**Comment by zhuzd12** [comment]
Yes, it takes about half an hour or even more to execute the code. I do know R isn't playing well whening dealing with double for loop, maybe I need to use batch-processing or call someother languages. I will put in effort to handle this kind of problems.
Plus, do I need to have my code commited to the Internet class?

**Comment by beyondpie** [comment]
1. U don't need to submit the codes to our internet class...
2. Rcpp is very powerful for enhancing the R codes. I also mention it in the discussion region of the internet class...

**Pull request closed without merging**
